### PR TITLE
able to send raw rpc methods

### PR DESCRIPTION
**Pull request by xlc**
#5299 take two

so we can send undecorated rpc calls
```js
const json = await api.rpc('exec_storageGet', 123, '0x12345678', '0x12345678');
```

### CODE REVIEW

**Comment by xlc** [comment]
The typing could be improved but not sure what's the better way
I would like to write some tests but can't find a good place for that and therefore have no idea if this actually works or not

**Comment by jacogr** [comment]
Brilliant. Sorry for not looking yet, the intent is indeed to get it into the next release.

**Review by jacogr — COMMENTED** [review]
One small comment, the rest looks sane.

**Review by jacogr — APPROVED** [review]
Thank you.

**Pull request merged**
