### PR TITLE
TransactionExtension, ExtrinsicV5

### PR DESCRIPTION
**Pull request by TarikGul**
ref: https://github.com/paritytech/polkadot-sdk/pull/3685

ExtrinsicV4 

- [X] Signed Transactions Work
- [X] Unsigned Transaction Work
- [x] No breaking Changes
    - Ensure there are no breaking changes in the current extrinsic construction workflow. This should only be checked off when this PR is ready to be merged.

ExtrinsicV5

- [x] Signed Transactions Work
    - [X] All payloads are hashed with blake2b
    - [x] Encodes signing payload correctly
    - [x] Decodes signing payload correctly
    - [x] Constructs and injects signatures correctly
    - [X] Correctly sets the preamble
    - [X] Correctly sets the Transaction Extension Version
    - [X] Tests
- [x] General Transaction Work
    - [x] Decode
    - [x] Encode
    - [x] Compatibility with ExtrinsicBase
- [x] Bare Transaction Work

## Tested Manually

- [X] Succesfully build and send a TX from scratch using `createType` with Preamble and Version options
- [X] Succesfully build and send a TX from scratch using `createType` WITHOUT Preamble and Version options
- [X] Submission through api.tx works
- [X] Apps can decode all tx's in explorer
- [X] Substrate-api-sidecar decodes blocks correctly

### CODE REVIEW

**Comment by bee344** [comment]
Something strange happens when I submit a `general` throught txwrapper: In the terminal I get 
```
Error: 1002 Verification Error: Runtime error: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
WASM backtrace:
error while executing at wasm backtrace:
    0: 0x6894f9 - rococo_runtime.wasm!rust_begin_unwind
    1: 0x12111 - rococo_runtime.wasm!core::panicking::panic_fmt::h791724d28dc2b8fe
    2: 0x5ac45a - rococo_runtime.wasm!TaggedTransactionQueue_validate_transaction: "RuntimeApi(\"Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed\\nWASM backtrace:\\nerror while executing at wasm backtrace:\\n    0: 0x6894f9 - rococo_runtime.wasm!rust_begin_unwind\\n    1: 0x12111 - rococo_runtime.wasm!core::panicking::panic_fmt::h791724d28dc2b8fe\\n    2: 0x5ac45a - rococo_runtime.wasm!TaggedTransactionQueue_validate_transaction\")"
    at /home/bee344/Documentos/parity/txwrapper-core/packages/txwrapper-examples/lib/txwrapper-examples/common/util.js:33:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (/home/bee344/Documentos/parity/txwrapper-core/packages/txwrapper-examples/lib/txwrapper-examples/polkadot/src/polkadot.js:110:26)
    ```
    But when I submit the same `hex` through `apps` `author.submitExtrinsic` I get 
    ```
    1011: Unknown Transaction Validity: UnknownTransaction::NoUnsignedValidator
    ```
    No idea why though.
    
    Tested with https://github.com/paritytech/txwrapper-core/tree/anp-test-transaction-ext . Last two commits work with the last two commits here, but for some reason general doesn't work with signed and viceversa

**Comment by gui1117** [comment]
AFAICT `NoUnsignedValidator` is only possible to be returned by bare extrinsic.

**Review by bee344 — APPROVED** [review]

**Comment by bkontur** [comment]
probably, related to this, see comment: https://github.com/paritytech/polkadot-sdk/pull/3685#pullrequestreview-2342656335

**Comment by TarikGul** [comment]
Small merging update - we found a small issue with how `api.tx` handles the calls. Looking into it (still planning on release today)

**Comment by bkontur** [comment]
> probably, related to this, see comment: [paritytech/polkadot-sdk#3685 (review)](https://github.com/paritytech/polkadot-sdk/pull/3685#pullrequestreview-2342656335)

cool, looks like this is working so far, 
could you please also release `api-cli` with this change https://github.com/polkadot-js/tools/tree/master/packages/api-cli ?

**Comment by TarikGul** [comment]
> > probably, related to this, see comment: [paritytech/polkadot-sdk#3685 (review)](https://github.com/paritytech/polkadot-sdk/pull/3685#pullrequestreview-2342656335)
> 
> cool, looks like this is working so far, could you please also release `api-cli` with this change https://github.com/polkadot-js/tools/tree/master/packages/api-cli ?

Yup, jumping into it now :)

**Pull request merged**
