### PR TITLE
Latest contract metadata

### PR DESCRIPTION
**Pull request by ascjones**
This PR is to demonstrate the new metadata format introduced via https://github.com/paritytech/ink/pull/296 which incorporates https://github.com/paritytech/scale-info/pull/3 (the parity fork of `type-metadata`). The main change is merging `type id` and `type def`.

This is a WIP and the main purpose is to test how easy it is to parse the updated format and gain some feedback before merging upstream, so any feedback appreciated.

- [x] Fix tests
- [x] Test sanitizing/handling of `Vec<u8>` -> `Bytes`
- [x] Fix lints
- [ ] Test integration with UI

### CODE REVIEW

**Comment by ascjones** [comment]
@jacogr you'll need to merge master into your branch to avoid the big diff.

Let me know if you have any feedback on the new format, since I am working towards getting the upstream PRs merged.

**Comment by jacogr** [comment]
@ascjones Master merged in. Sorry, I completely forgot :(

**Comment by jacogr** [comment]
It looks fine to merge into mine. I would love a larger ABI test case though (only 7 types here, but can wait for that, should not stop this). Some additional type naming cleanups can be done (once again, not for here), e.g. removing the indexes, which are certainly not useful anymore.

**Comment by ascjones** [comment]
Have removed the indices. I'd like to test it with the UI if possible - can you point me to where it hooks in?

**Comment by jacogr** [comment]
For the UI test, there is the `./copy-to-apps.sh` script - compiles and copies it t the apps UI. the a `yarn start` inside the apps repo will launch.

copy script does assume the api and apps are on the same level, i.e. `/home/me/Projects/{api, apps}`

**Pull request merged**
