### PR TITLE
Support non payable

### PR DESCRIPTION
**Pull request by achimcc**
Adds support for non-payable Smart Contract constructors to api-contract, as dicussed in https://github.com/polkadot-js/apps/issues/6645

### CODE REVIEW

**Comment by jacogr** [comment]
See https://github.com/polkadot-js/api/pull/4432

**Comment by achimcc** [comment]
Solved by #4432

**Comment by jacogr** [comment]
Sorry for beating you to it, I would have preferred something not by me, but had a gap earlier while waiting for CI elsewhere so logged and PR-ed it.

**Comment by achimcc** [comment]
> Sorry for beating you to it, I would have preferred something not by me, but had a gap earlier while waiting for CI elsewhere so logged and PR-ed it.

No worries. I'll leave a comment and open a draft PR earlier next time, I'll pick up an issue ;)

**Pull request closed without merging**
