### PR TITLE
Updated child storage parameters

### PR DESCRIPTION
**Pull request by Stefie**
Fixes https://github.com/polkadot-js/api/issues/1679

I ran `yarn run docs` because I noticed the docs are checked in, but happy to revert the files if that's not the workflow.

It can't really be tested at the moment, because the only two pallets using child_storage are pallet_contracts in substrate and the crowdfunding module for parachains in Kusama.

### CODE REVIEW

**Comment by jacogr** [comment]
No docs, please.

**Comment by Stefie** [comment]
Ok, reverted.

**Comment by Stefie** [comment]
If that is all that is needed to get the new childStorage parameters in, it would be great if we could merge it! We're making use of the JS API for contract development and it's currently broken and not really usable for us with newer Substrate versions because of the additional parameters.

**Comment by jacogr** [comment]
???

This is nowhere near merge-able -

- Linting fails
- Build fails

We are not breaking master, if this gets merged nothing will publish.

**Comment by Stefie** [comment]
Yup, sorry, that was actually a quick shot... The linting failed on the tests, which were broken before and Amaury told me that they're most likely going to be removed soon anyways, that's why I didn't pay closer attention.
I'm testing it with with ink! and contracts now to help to pin down @Robbepop's bug

**Pull request merged**
