### PR TITLE
make ts generate script more reusable

### PR DESCRIPTION
**Pull request by xlc**
Minimum amount of work to make the generate ts script somewhat reusable.
May have more followup changes when I start actually integrating this tomorrow.

Relates: #1223

### CODE REVIEW

**Comment by jacogr** [comment]
Thank you very much.

**Comment by xlc** [comment]
Should be good now. This is the other side of the work: https://github.com/laminar-protocol/orml.js/pull/1

**Comment by jacogr** [comment]
Perfect, thank you as always! I will give it a play-through today.

**Comment by xlc** [comment]
@jacogr Can you merge this? It generates identical code for polkadot/substrate.

**Comment by jacogr** [comment]
My appologies, I'm aware of this one (along with a bunch of others in my queue), however have not gotten around to testing yet, I'm currently stuck on rapid-fire Substrate/Polkadot changes atm. Hoping to catch a breath to clear the queue.

**Pull request merged**
