### PR TITLE
fix: broken links in readme

### PR DESCRIPTION
**Pull request by yjkimjunior**

### CODE REVIEW

**Comment by yjkimjunior** [comment]
erm, so here fixing the README path breaks the doc generation, and vice versa?

**Comment by jacogr** [comment]
It is there for the doc generation, yes. There are some tricks that can be done to hide completely in GH-mode which can probably be explored. (Since md is just HTML, can wrap less useful content in a div, hide by default, show in docs. Would need to apply everywhere)

**Comment by jacogr** [comment]
No easy fix, tries a couple of options in #2409 & #2410 

So it will have to stay non-navigatable until a better idea comes along.

**Comment by jacogr** [comment]
I guess the only option left here is o not use the README.md in the package for the docs, but rather craft 2 seperate versions and use appropriately. (There would be some tweaks to the doc building process, which will also affect the common & ui repos)

**Pull request closed without merging**
