### PR TITLE
Convert contract e2e to flipper

### PR DESCRIPTION
**Pull request by jacogr**
Tested against current substrate master as-is (and also via the UI)

### CODE REVIEW

**Comment by Stefie** [comment]
Are the INK! files from @pepyakin ? He just sent me the same to test `child_storage`

**Comment by jacogr** [comment]
Keith compiled these. But it the standard flipper contract.

**Comment by Stefie** [comment]
Test 2 and 3 are failing for me with Pierres commit https://github.com/paritytech/substrate/commit/76e03c7df457982295782f62eaee12c9d5a07dbf from yesterday evening.
`codeHash` is not defined in ` Promise e2e contracts › incrementer › allows contract create` and
`address` is not defined in `Promise e2e contracts › incrementer › allows contract call`

**Comment by jacogr** [comment]
Did you purge the chain before and between runs?

**Comment by Stefie** [comment]
Yes, I did a `./target/release/substrate purge-chain --dev`.
I'm just compiling it without `--release`.

**Comment by Stefie** [comment]
^^ Same result.

**Comment by Stefie** [comment]
Ah, ok, that explains why the first test was failing too when compiled without `--release`. 
So with I get the failing thests with:
https://github.com/paritytech/substrate/commit/76e03c7df457982295782f62eaee12c9d5a07dbf
`./target/release/substrate purge-chain --dev`
`./scripts/build.sh && cargo build --release`
`cargo run --release \-- --dev`

**Comment by jacogr** [comment]
Ok, rebuilding current master, things cannot break overnight... well, it _is_ master :)

**Comment by jacogr** [comment]
Ok, I give up, however have bumped the `putCode` gas, that _may_ make a difference. On current master (just freshly finished compiling), 

```
Test Suites: 1 passed, 1 total
Tests:       4 passed, 4 total
Snapshots:   0 total
Time:        14.451s, estimated 15s
```

**Pull request merged**
