### PR TITLE
Nits from PR #936

### PR DESCRIPTION
**Pull request by Stefie**
Small follow-up enhancements

- https://github.com/polkadot-js/api/pull/936#discussion_r287823355
- https://github.com/polkadot-js/api/pull/936#discussion_r287823281
- https://github.com/polkadot-js/api/pull/936#discussion_r287823484
- https://github.com/polkadot-js/api/pull/936#discussion_r287823553

### CODE REVIEW

**Comment by Stefie** [comment]
The suggested changes in the comments mentioned in the description all throw `Codec` errors in the type of:

```
Argument of type 'xyz' is not assignable to parameter of type 'xyz'.
  Type 'Codec' is missing the following properties from type 'xyz': _bitLength, _isHexJson, _isNegative, bitLength, and 84 more.
```

@amaurymartiny , @jacogr any Ideas how to solve that?

**Comment by jacogr** [comment]
Seems to be the `switchMap`s from your other comment -

```js
Argument of type 'OperatorFunction<Header, Codec>' is not assignable to parameter of type 'OperatorFunction<Codec, Codec>'.
Type 'Codec' is missing the following properties from type 'Header': blockNumber, digest, extrinsicsRoot, hash, and 20 more.
```

**Comment by Stefie** [comment]
Your suggested approach works, just  unfortunately not for `Vector<EventRecord>`

**Comment by jacogr** [comment]
Weird, Vector is a Codec. O, well, live for fight another day.

**Pull request merged**
