### PR TITLE
Update EthereumRuntimeRPCApi to V5

### PR DESCRIPTION
**Pull request by timbrinded**
Updates `EthereumRuntimeRPCApi` to support the WeightV2 implementation.

- Fixes https://github.com/polkadot-js/api/issues/5679

### CODE REVIEW

**Comment by jacogr** [comment]
Thank you. Just give me a day or two to get a breather and do a proper look.

**Comment by timbrinded** [comment]
Any news on this? We have a runtime that uses the updated EthereumApi going live soonish

**Comment by timbrinded** [comment]
Gentle reminder @jacogr about this PR 😸

**Comment by crystalin** [comment]
Hi @jacogr , sorry to ping you again but this is becoming a blocker for us to move forward, did you get a chance to look at it or is there anything we can do to help on that side ?

**Review by jacogr — APPROVED** [review]
Looks spot-on, thank you.

**Pull request merged**
