### PR TITLE
Added FungiblesApi version 2

### PR DESCRIPTION
**Pull request by bkontur**
tested locally and works:

Screenshot from 2023-07-10 11-24-46

### CODE REVIEW

**Comment by bkontur** [comment]
@jacogr 
how should I fix this failing [test](https://github.com/polkadot-js/api/actions/runs/5506453022/jobs/10035144851?pr=5687)? 

I tried to add:
```
import type { XcmVersionedMultiAssets } from '@polkadot/types/lookup';
```
but this does not even compile locally:
```
$ tsc --build tsconfig.build.json
packages/types/src/interfaces/fungibles/runtime.ts:5:1 - error TS6133: 'XcmVersionedMultiAssets' is declared but its value is never read.

5 import type { XcmVersionedMultiAssets } from '@polkadot/types/lookup';
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

packages/types/src/interfaces/fungibles/runtime.ts:5:15 - error TS2305: Module '"@polkadot/types/lookup"' has no exported member 'XcmVersionedMultiAssets'.

5 import type { XcmVersionedMultiAssets } from '@polkadot/types/lookup';
                ~~~~~~~~~~~~~~~~~~~~~~~


Found 2 errors.

Error: Command failed: yarn polkadot-exec-tsc --build tsconfig.build.json
    at checkExecSyncError (node:child_process:885:11)
    at Object.execSync (node:child_process:957:15)
    at execSync (file:///home/bparity/parity/polkadot-js/api/node_modules/@polkadot/dev/scripts/util.mjs:164:6)
    at main (file:///home/bparity/parity/polkadot-js/api/node_modules/@polkadot/dev/scripts/polkadot-dev-build-ts.mjs:1348:3)
    at file:///home/bparity/parity/polkadot-js/api/node_modules/@polkadot/dev/scripts/polkadot-dev-build-ts.mjs:1395:1
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 201977,
  stdout: null,
  stderr: null
}
node:internal/errors:868
  const err = new Error(message);
              ^

Error: Command failed: yarn build
    at checkExecSyncError (node:child_process:885:11)
    at Object.execSync (node:child_process:957:15)
    at execSync (file:///home/bparity/parity/polkadot-js/api/node_modules/@polkadot/dev/scripts/util.mjs:164:6)
    at file:///home/bparity/parity/polkadot-js/api/node_modules/@polkadot/dev/scripts/polkadot-dev-copy-to.mjs:25:1
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25) {
  status: 255,
  signal: null,
  output: [ null, null, null ],
  pid: 201607,
  stdout: null,
  stderr: null
}

Node.js v19.3.0

```

**Comment by bkontur** [comment]
@jacogr could be related to this [comment](https://github.com/polkadot-js/api/pull/5584#discussion_r1159497233) ?

**Comment by bkontur** [comment]
@jacogr ok, I found it and going to fix it like [here](https://github.com/polkadot-js/api/pull/5592#issuecomment-1508273951)

**Comment by bkontur** [comment]
@jacogr ok, now it is ready and everything passed

**Review by jacogr — APPROVED** [review]
Thank you.

**Pull request merged**
