### PR TITLE
Temporary solution for missing parameter_types

### PR DESCRIPTION
**Pull request by Stefie**
Resolves https://github.com/polkadot-js/api/issues/1064.

Has some follow up tasks once https://github.com/polkadot-js/api/pull/1066 is merged. Marked with
`// @TODO replace this with calls to `api.consts` once implemented`
in the code.

I also added some tests as part of  https://github.com/polkadot-js/api/issues/868 and added some code comments for JSDOC https://github.com/polkadot-js/api/issues/603

### CODE REVIEW

**Comment by amaurymartiny** [comment]
#1066 is 95% finished, so if you want to start rebasing on top of that i think it's safe now.

**Comment by Stefie** [comment]
Great, will give it a shot!

**Comment by Stefie** [comment]
Ah, no, @axelchalon  actually pinged me on Riot yesterday evening saying that the PR doesn't work with the latest substrate yet, only with the slightly outdated static version of the metadata. Since there have been no commits since then I'd guess that that's still the case.

**Comment by axelchalon** [comment]
turns out it was my node which had a problem (served outdated metadata), so I think in the end my PR as it stands should still work with latest substrate. wrapping it up this afternoon anyway.

**Comment by Stefie** [comment]
:) Ok, I'll just give it a try and roll back if things break!

**Pull request closed without merging**
