### PR TITLE
Rewrite SubmittableExtrinsic.ts (close #1045)

### LINKED ISSUE #1045: Rewrite SubmittableExtrinsic.ts
This file: https://github.com/polkadot-js/api/blob/master/packages/api/src/SubmittableExtrinsic.ts

It's hard to maintain, everytime I read this file, I need a 10 good minutes to get what it's doing.

Some ideas:
- Only use TS classes (loaded at runtime, but still possible), no `Object.defineProperties`
- See if `decorateMethod` can be less hacky inside
- https://github.com/polkadot-js/api/blob/5e5bb9984b1f42f0dbc3b4d42a41fdb17aa60898/packages/api/src/SubmittableExtrinsic.ts#L69-L71

How do I pass in options and a callback?
- https://github.com/polkadot-js/api/blob/5e5bb9984b1f42f0dbc3b4d42a41fdb17aa60898/packages/api/src/SubmittableExtrinsic.ts#L79
This seems to be used nowhere...

### PR DESCRIPTION
**Pull request by axelchalon**
close https://github.com/polkadot-js/api/issues/1045

### CODE REVIEW

**Comment by axelchalon** [comment]
cf failing travis build / tsc : no idea why `typeof _options extends Callback<ISubmittableResult>` isn't matched for `signAndSend (account: IKeyringPair | string | AccountId | Address, _options?: Partial<SignatureOptions> | Callback<ISubmittableResult>, statusCb?: Callback<ISubmittableResult>)` when calling it with `.signAndSend(keyring.alice, ({ status }: SubmittableResult) => { ... }`

**Comment by ianhe8x** [comment]
SubmittableExtrinsic used to extends Extrinsic like the change you made, i changed it to use Object.defineProperties because in our project we have custom extrinsic implementation. you can check `https://github.com/polkadot-js/api/pull/739` for more info.

**Comment by jacogr** [comment]
Yes, Ian is right - we should not extend it, specifically for the reasons mentioned, ie. Custom extrinsic implementations. (We are Not just catering for Polkadot and simple substrate chains here)

**Comment by ianhe8x** [comment]
I did another version(#1083 ), feedback welcomes.

**Comment by ianhe8x** [comment]
this DynamicExtrinsicSubmittable ideally  only need to be created once, maybe we can store it in base as a protected member and reuse

**Comment by ianhe8x** [comment]
i just think of some cases it will be handy if i have access to it, so i can do some thing with its prototype

**Comment by axelchalon** [comment]
actually, what prevents us from registering DynamicExtrinsicSubmittable inside the TypeRegistry? i.e. having `SubmittableExtrinsic` in `@polkadot/types` just like `Extrinsic`; only downside I see is that if we register a custom extrinsic, we also have to register a custom submittableextrinsic. is this it?

**Comment by ianhe8x** [comment]
Only problem is there would be two SubmittableExtrisic, one for PromiseApi the other for Rx

**Comment by axelchalon** [comment]
> Yes, Ian is right - we should not extend it, specifically for the reasons mentioned, ie. Custom extrinsic implementations. (We are Not just catering for Polkadot and simple substrate chains here)

gotcha, but extending the dynamically fetched Extrinsic class from the type registry (like now this in PR) should be ok, or?

**Comment by axelchalon** [comment]
cc @jacogr does the code of this PR look good and do we want to merge it? if so I'll merge from master and fix the conflicts. else we can close the PR

**Comment by jacogr** [comment]
So, things have changed quite a bit... which actually means what you set out to do initially is now actually possible.

Look at `api-derive/type/HeaderExtended`, it extends via `ClassOf('Header')` which pulls the Header from the registry.

**Pull request closed without merging**
