### PR TITLE
refactor: Fixes #241. Rename from RxApi to ApiRx in api/rx types

### LINKED ISSUE #241: Rename from RxApi to ApiRx in api-rx types
We have been using `ApiRx` to refer to api-rx. However types defined for api-rx are prefixed with `RxApi` instead of `ApiRx`

Action is to
* rename `RxApiInterface$Events` to `ApiRxInterface$Events`
* rename `RxApiInterface` to `ApiRxInterface`

### PR DESCRIPTION
**Pull request by ltfschoen**

### CODE REVIEW

**Comment by jacogr** [comment]
@ltfschoen Merged in master, CI doesn't like something :(

**Comment by ltfschoen** [comment]
@jacogr I've fixed that conflict

**Comment by jacogr** [comment]
+0 lines, -0 lines - so I guess we catered for it along the way

**Comment by jacogr** [comment]
Closing, no files or lines added/removed

**Pull request closed without merging**
